import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="flex fixed items-center justify-between top-0 left-0 right-0 z-10 bg-black text-white p-4  ">
          <h1 className="
        text-4xl font-bold tracking-tight
        ">
            Rice_Hack
          </h1>
          <div className="
        w-12 h-12 bg-gray-300 rounded-full border-4 border-white
        "/>
        </header>

        {children}
      </body>
    </html>
  );
}
