import type { Metadata } from "next";
import "./globals.css";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Separator } from "@/components/ui/separator";
import { Circle, Menu, User } from "lucide-react";
import React from "react";
import { AuthProvider } from "@/context/AuthContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ナビゲーションアイテムの定義
type NavigationItem = {
  icon: React.ElementType;
  label: string;
  active: boolean;
};

const navigationItems: NavigationItem[] = [
  {
    icon: Menu,
    label: "TimeLine",
    active: false,
  },
  {
    icon: Circle,
    label: "Record",
    active: false,
  },
  {
    icon: User,
    label: "Profile",
    active: true,
  },
];




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <AuthProvider>
        
        <header className="flex fixed items-center justify-between top-0 left-0 right-0 z-10 bg-black text-white p-4  ">
          <h1 className="
        text-4xl font-bold tracking-tight
        ">
            Rice_Hack
          </h1>
          <div className="
        w-12 h-12 bg-gray-300 rounded-full border-4 border-white
        "/>
        </header>
        {/* ナビゲーションバーを画面下部に固定 */}
        <nav className="fixed bottom-0 flex items-center justify-center gap-6 p-4 rounded-t-xl shadow-md bg-white z-10">
          {navigationItems.map((item, index) => (
            <React.Fragment key={index}>
              <Button
                variant="ghost"
                className={`flex items-center gap-2 p-2 ${item.active ? 'bg-gray-200' : ''}`}
              >
                <item.icon className={`w-5 h-5 ${item.active ? 'text-blue-600' : 'text-black'}`} />
                <span
                  className={`text-xl font-normal ${item.active ? 'text-blue-600 font-semibold' : 'text-black'}`}
                >
                  {item.label}
                </span>
              </Button>
              {index < navigationItems.length - 1 && (
                <Separator orientation="vertical" className="h-8 w-px bg-gray-400" />
              )}
            </React.Fragment>
          ))}
        </nav>

        {children}
        
        </AuthProvider>
      </body>
    </html>
  );
}
